on:
  pull_request:
    branches: 
    - 'AlexAntn/add_app*'
    types: [closed]
  push:
    branches: 
    - 'add_app*'

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: say_hello
        run: echo "hello"
