name: trigger_issue

on:
  issues:
    types: [pinned]    

jobs:
 dump:
  runs-on: ubuntu-latest
  steps:
  - name: $github
    run:   |
        echo ${{ github.event.comment.body }}
        echo ${{ github.event.comment }}
        echo ${{ github.event }}
        echo ${{ github }}
#        echo "$GITHUB_CONTEXT"
    env:
     GITHUB_CONTEXT: ${{ toJson(github) }}
