name: trigger_issue

on:
  issues:
    types: [pinned]    

jobs:
 dump:
  runs-on: ubuntu-latest
  steps:
  - name: $github
    run:   |
        echo "${{ github.event.issue.body }}"
        echo "${{ toJson(github.event.issue) }}"
        echo "${{ toJson(github.event) }}"
        echo "${{ toJson(github) }}"
#        echo "$GITHUB_CONTEXT"
    env:
     GITHUB_CONTEXT: ${{ toJson(github) }}
