name: trigger_issue

on:
  issues:
    types: [pinned]    

jobs:
 dump:
  runs-on: ubuntu-latest
  steps:
  - name: $github
    run:   |
        echo "${{ github.event.issue.body }}"
        echo "${{ toJson(github) }}"
  - name: get date
    run: |
      echo "$(date +'%Y%m')" > DATE_
      echo $(cat DATE_)     
      echo "$(date +'%B %Y')" > DATE_SPELLED
      echo $(cat DATE_SPELLED)   

  - name: Repository Dispatch
    uses: peter-evans/repository-dispatch@v1
    env:
      DATE_: ${{ $(cat DATE_) }}
      DATE_SPELLED: ${{ $(cat DATE_SPELLED) }}
    with:
      token: ${{ secrets.TOKEN_VALUE_HERE }}
      repository: AlexAntn/test_actions
      event-type: announcement_launched
      client-payload: '{"description": ${{ toJson(github.event.issue.body) }}, "id": ${{ env.DATE_ }}, "title": ${{ toJson(github.event.issue.title) }}, "date": ${{ env.DATE_SPELLED }}, "summary": "???", "image": "???", "type" : "announcement_launched"}'
