name: trigger_issue

on:
  issues:
    types: [pinned]    

jobs:
 dump:
  runs-on: ubuntu-latest
  steps:
  - name: $github
    run:   |
        echo "${{ github.event.issue.body }}"
        echo "${{ toJson(github) }}"

  - name: get release/announcement
    id: rel_annou
    run: |
      if [[ ${{ github.event.issue.title }} == "*Release*" ]];
      then
        echo "::set-output name=release::'true'"
      else
        echo "::set-output name=release::'false'"
      fi
  - name: Get current date
    id: date
    run: |
        echo "::set-output name=date::$(date +'%Y%m')"
        echo "::set-output name=date_spelled::$(date +'%B %Y')"

  - name: Repository Dispatch
    uses: peter-evans/repository-dispatch@v1
    with:
      token: ${{ secrets.TOKEN_VALUE_HERE }}
      repository: AlexAntn/test_actions
      event-type: announcement_launched
      client-payload: '{"description": ${{ toJson(github.event.issue.body) }}, "id": "${{ steps.date.outputs.date }}", "title": ${{ toJson(github.event.issue.title) }}, "date": "${{ steps.date.outputs.date_spelled }}", "summary": "???", "image": "???", "type" : "announcement_launched", "release": "${{ steps.rel_annou.outputs.release }}"}'
