name: trigger

on: push

jobs:
    job_id: 
        runs-on: [ubuntu-latest]
        steps:
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v1
          with:
            token: ${{ secrets.TOKEN_VALUE_HERE }}
            repository: icub-tech-iit/code
            event-type: trigger
            #client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
