name: trigger

on: push

jobs:
    job_id: 
        runs-on: [ubuntu-latest]
        steps:
            - run: |
                chmod +x ./action/entrypoint.sh
                sh ./action/entrypoint.sh
