name: trigger

on: push

jobs:
    job_id: 
        runs-on: [ubuntu-latest]
        steps:
        - name: Get the version
          id: get_version
          run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v1
          with:
            token: ${{ secrets.TOKEN_VALUE_HERE }}
            repository: AlexAntn/test_actions
            event-type: trigger
            client-payload: '{"version": "${{ steps.get_version.outputs.VERSION }}"}'
