name: trigger_issue

on: push 


jobs:
    job_id: 
        runs-on: [ubuntu-latest]
        steps:
        - name: Get the version
          id: get_version
          run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v1
          with:
            token: ${{ secrets.APPSAWAY_REPO_ACCSS_TOKEN }}
            repository: icub-tech-iit/code
            event-type: release_trigger
            client-payload: '{"version": "v2022.02.0"}'


