name: trigger_issue

on:
  issues:
    types: [pinned]    

jobs:
 dump:
  runs-on: ubuntu-latest
  steps:
  - name: $github
    run:   |
        echo "${{ github.event.issue.body }}"
  - name: Repository Dispatch
    uses: peter-evans/repository-dispatch@v1
    with:
      token: ${{ secrets.TOKEN_VALUE_HERE }}
      repository: AlexAntn/test_actions
      event-type: announcement-launched
      client-payload: '{"announcement": "${{ github.event.issue.body }}", "type": "announcement"}'
