name: trigger

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
        - name: 'Repository dispatch',
          uses: defold/repository-dispatch@1.1.4,
          with: {
            repo: 'org/repo',
            token: '${{ secrets.TOKEN }}',
            user: 'john.smith@acme.com',
            action: 'my-action'
            client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
        }
    
