name: trigger

on: push

jobs:
    job_id: 
        runs-on: [ubuntu-latest]
        steps:
            - name: Repository Dispatch
              uses: actions/repository-dispatch@v1.0.0
              with:
                    token: ${{ secrets.TOKEN_VALUE_HERE }}
                    repository: username/my-repo
                    event-type: my-event
                    client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
