name: trigger

on: push

jobs:
    job_id: 
        runs-on: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - run: |
                chmod +x ./action/entrypoint.sh
                sh ./action/entrypoint.sh
