name: trigger_repo

on: 
    push:
    #release:
        #types: [published, created, edited]        

jobs:
    job_id: 
        runs-on: [ubuntu-latest]
        steps:
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v1
          with:
            token: ${{ secrets.CODE_REPO_TOKEN }}
            repository: icub-tech-iit/code
            event-type: repository_trigger
            client-payload: '{"type": "repository_trigger", "img_list": "ubuntu2004mesa"}'
